### ISSUE TITLE
Maßstabsanzeige

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#5]
# Status quo
Es wird kein Maßstab angezeigt. 

# Improvement
```javascript
MapOpenLayers.js, Z. 127ff:

...

	// Map
	this.map = new ol.Map
	(
		{
			target: this.root,
			view: this.view,
			pixelRatio: 1.0,
			moveTolerance: 5,
			controls: [
				new ol.control.ScaleLine(),    /* add initial scale line */
			]
		}
	);
...


```

Damit Attribution nicht überlagert zusätzlich noch
```css
Attribution.css:

.netgis-attribution
{
	position: absolute;
	right: 0mm;      /* change left to right*/
	bottom: 0mm;
	padding: 1mm;
	background: rgba( 255, 255, 255, 0.5 );
	/*color: #a7233f;*/
	font-size: 0.8em !important;
	z-index: 100;
}


```
